name: Build and Publish package to GitHub Packages
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Get version
        id: version
        run: |
          echo "parsing version from ref '$GITHUB_REF'"

          VERSION=$(echo "$GITHUB_REF"  | sed -e "s|refs/tags/||g" | sed -E 's/v?([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z]+(\.[0-9]+)?)?/\1.\2.\3\4/g')
          echo "version: '$VERSION'"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update Version
        run: |
          echo "updating version to '$VERSION'"
          mvn -B versions:set "-DnewVersion=$VERSION"
      - name: Make AST preprocessor
        working-directory: parser
        run: make build
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v1'
          args: release --snapshot
          workdir: ./parser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


